// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9veCDeodL87QObk_JXfVvdNvG-JQKafU',
    appId: '1:709692300821:web:c1a98ddd1a2730a229381c',
    messagingSenderId: '709692300821',
    projectId: 'book-my-etaxi',
    authDomain: 'book-my-etaxi.firebaseapp.com',
    databaseURL: 'https://book-my-etaxi-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'book-my-etaxi.appspot.com',
    measurementId: 'G-3JDTZ4YQ3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmhfTVZULPMgosgbUaZLgdOvkpXRUisO4',
    appId: '1:709692300821:android:f7ca396b04a1070a29381c',
    messagingSenderId: '709692300821',
    projectId: 'book-my-etaxi',
    databaseURL: 'https://book-my-etaxi-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'book-my-etaxi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD__CrnMNWJ3F0L4tEOcYRuaTkH8Cd5HYU',
    appId: '1:709692300821:ios:7909e3d8ef7643e229381c',
    messagingSenderId: '709692300821',
    projectId: 'book-my-etaxi',
    databaseURL: 'https://book-my-etaxi-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'book-my-etaxi.appspot.com',
    androidClientId: '709692300821-05h4k1odl5lhla48m5b9o5mt73g8ogdr.apps.googleusercontent.com',
    iosClientId: '709692300821-rhdsd0jgltgm5dn1k0h5ai638rlt1egg.apps.googleusercontent.com',
    iosBundleId: 'com.bmet.customerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD__CrnMNWJ3F0L4tEOcYRuaTkH8Cd5HYU',
    appId: '1:709692300821:ios:7909e3d8ef7643e229381c',
    messagingSenderId: '709692300821',
    projectId: 'book-my-etaxi',
    databaseURL: 'https://book-my-etaxi-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'book-my-etaxi.appspot.com',
    androidClientId: '709692300821-05h4k1odl5lhla48m5b9o5mt73g8ogdr.apps.googleusercontent.com',
    iosClientId: '709692300821-rhdsd0jgltgm5dn1k0h5ai638rlt1egg.apps.googleusercontent.com',
    iosBundleId: 'com.bmet.customerapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApVit6F-av3sNZA0PzteHbSNLOBer8UlE',
    appId: '1:709692300821:web:ea3343bbc0a1ebc729381c',
    messagingSenderId: '709692300821',
    projectId: 'book-my-etaxi',
    authDomain: 'book-my-etaxi.firebaseapp.com',
    databaseURL: 'https://book-my-etaxi-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'book-my-etaxi.appspot.com',
    measurementId: 'G-YS3YHNC804',
  );
}
